services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ~/Gestion_Apprenant_laravel/Apprenant:/var/www/html
      - /storage/app/apprenant-laravel-firebase-adminsdk-3pqj9-315a6c8b89.json # Mount the storage directory
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5433
      DB_DATABASE: gestion_apprenant
      DB_USERNAME: thomas
      DB_PASSWORD: aadeldiablo10
      APP_PORT: 8080
      FIREBASE_KEY_BASE64: your_base64_encoded_key_here
      GOOGLE_APPLICATION_CREDENTIALS: /var/www/firebase-key.json
    expose:
      - "8080"  # Ensure the application listens on this port

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/sites-enabled/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: gestion_apprenant
      POSTGRES_USER: thomas
      POSTGRES_PASSWORD: aadeldiablo10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
